package: naju_contact_info
version: '0.0.3'
author: NAJU Sachsen
supportpage: https://github.com/NAJU-Sachsen/rex-contact-info
requires:
  redaxo: '^5.10'
  php: '>=7.1'
  packages:
    naju_group_accounts: '>=0.0.1'
page:
  title: 'Kontakt-Informationen'
  icon: rex-icon fa-address-card
